Repository PomegranateBlue/dont_worry, pull requests merged in 2025-04, with the labels that each got.

#6 🎉 add / Supabase 타입 재설정 및 ChatGPT API 디자인 패턴 적용
  1.8.1
  database.types.ts
  package-lock.json
  src/app/page.tsx
  src/app/utils/supabase/db.ts
  src/components/main/atoms/Button.tsx
  src/components/main/atoms/TextArea.tsx
  src/components/main/atoms/inputField.tsx
  src/components/main/atoms/submitButton.tsx
  src/components/main/modules/ChatTemplate.tsx
  src/components/main/modules/chatBox.tsx
  src/components/main/molecules/InputForm.tsx
  src/components/main/molecules/messageItem.tsx
  src/components/main/organisms/ChatBox.tsx
  src/components/main/organisms/chatForm.tsx
  src/components/main/organisms/messageList.tsx
  src/constants/openai/category.ts
  src/constants/openai/commentconfig.ts
  src/types/openai/openaiType.ts
  supabase/.gitignore
  supabase/config.toml
Labels: 제우, feat

#7 Ranking
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/app/ranking/emotions-rank/page.tsx
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/app/utils/supabase/supabase.ts
  src/components/header.tsx
  src/components/ranking/Chart.tsx
  src/components/ranking/FilterMenu.tsx
  src/components/ranking/RankingHeader.tsx
  src/components/ranking/WeekNavigator.tsx
Labels: 원택, feat

#10 ✨ update / 걱정 작성 페이지 일부 기능 수정
  components.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/mypage/page.tsx
  src/app/note/(steps)/category/page.tsx
  src/app/note/(steps)/message/page.tsx
  src/app/note/(steps)/result/page.tsx
  src/app/note/layout.tsx
  src/app/note/page.tsx
  src/app/page.tsx
  src/app/utils/supabase/db.ts
  src/components/header.tsx
  src/components/main/atoms/inputField.tsx
  src/components/main/atoms/submitButton.tsx
  src/components/main/modules/chatBox.tsx
  src/components/main/molecules/messageItem.tsx
  src/components/main/organisms/chatForm.tsx
  src/components/main/organisms/messageList.tsx
  src/components/noteComponents/categorySelector.tsx
  src/hooks/useMyPageQueries.ts
  tailwind.config.ts
Labels: 제우, feat

#11 Ranking
  src/app/ranking/emotions-rank/page.tsx
  src/app/ranking/layout.tsx
  src/components/ranking/RankingHeader.tsx
  src/components/ranking/WeekNavigator.tsx
  src/store/store.ts
Labels: 원택, feat

#14 feat : 로그인,회원가입,로그아웃
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/(auth)/action.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/test/page.tsx
  src/app/error/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/app/utils/supabase/client.ts
  src/app/utils/supabase/middleware.ts
  src/app/utils/supabase/server.ts
  src/components/header.tsx
  src/components/header/LogOutButton.tsx
  src/middleware.ts
Labels: 혜린, feat

#15 🎉add/ letter 컴포넌트 생성
  src/app/letter/page.tsx
  src/components/LetterForm.tsx
  src/types/supabase/supabase.ts
Labels: 정빈, feat

#16 ✨ update / zustand를 통한 사용자 입력 창 관리 완료
  src/app/note/(steps)/category/page.tsx
  src/app/note/(steps)/message/page.tsx
  src/app/note/(steps)/result/page.tsx
  src/app/note/page.tsx
  src/app/page.tsx
  src/app/utils/openai/route.ts
  src/components/header.tsx
  src/components/noteComponents/EmotionCategoryForm.tsx
  src/components/noteComponents/MessageForm.tsx
  src/components/noteComponents/ResultForm.tsx
  src/components/noteComponents/StepFlow.tsx
  src/components/noteComponents/TopicCategoryForm.tsx
  src/components/noteComponents/categorySelector.tsx
  src/lib/api/gpt/gpt.ts
  src/store/noteStore.ts
Labels: 제우, feat

#19 Mypage
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/app/utils/supabase/db.ts
  src/hooks/useMyPageQueries.ts
Labels: 익환, feat

#18 [feat]Login : 로그인 상태에 따른 헤더 조건부 렌더링
  src/app/(main)/layout.tsx
  src/app/auth/action.ts
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/app/utils/supabase/middleware.ts
  src/app/utils/supabase/server.ts
  src/components/header.tsx
  src/components/loginComponents/LogOutButton.tsx
Labels: 혜린, feat

#20 Ranking
  package-lock.json
  pnpm-lock.yaml
  src/app/ranking/emotions-rank/page.tsx
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/app/utils/ranking/DataFetch.ts
  src/app/utils/ranking/RankingFilter.ts
  src/components/ranking/BetterThing.tsx
  src/components/ranking/Chart.tsx
  src/components/ranking/EmotionsChart.tsx
  src/components/ranking/FilterMenu.tsx
  src/components/ranking/Report.tsx
  src/components/ranking/TopicChart.tsx
  src/components/ranking/WeekNavigator.tsx
  src/components/ranking/WorsenedThing.tsx
  src/components/ranking/solution.tsx
  src/constants/ranking/ChartOptions.ts
  src/constants/ranking/Line.ts
  src/hooks/ranking/useAnalysisTrend.ts
  src/lib/utils.ts
  src/store/ranking/rankingStore.ts
  src/store/store.ts
  src/types/ranking/types.ts
Labels: 원택, feat

#29 ✨update / 이미지 추가하여 letter 테이블에 편지 내용과 함께 저장
  pnpm-lock.yaml
  src/app/(main)/layout.tsx
  src/app/letter/page.tsx
  src/components/LetterForm.tsx
  src/components/letterComponents/LetterForm.tsx
Labels: 정빈, feat

#30 Ranking
  src/app/ranking/emotions-rank/page.tsx
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/app/utils/supabase/db.ts
  src/components/ranking/BetterThing.tsx
  src/components/ranking/EmotionsChart.tsx
  src/components/ranking/FilterMenu.tsx
  src/components/ranking/FusionComp/MWreportCard.tsx
  src/components/ranking/MWFilter.tsx
  src/components/ranking/Report.tsx
  src/components/ranking/TopThreeCard.tsx
  src/components/ranking/TopicChart.tsx
  src/components/ranking/WeekNavigator.tsx
  src/components/ranking/WorsenedThing.tsx
  src/components/ranking/solution.tsx
  src/constants/ranking/Line.ts
Labels: 원택, feat, css

#32 ✨update / 미래편지 작성 컴포넌트 분리 후 조건부 렌더링, 모바일 시안 적용
  next.config.mjs
  src/app/letter/page.tsx
  src/components/letterComponents/CalendarStep.tsx
  src/components/letterComponents/LetterForm.tsx
  src/components/letterComponents/LetterStep.tsx
Labels: 정빈, feat, css

#52 Ranking
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/ranking/emotions-rank/page.tsx
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/app/utils/ranking/RankingFilter.ts
  src/components/ranking/BetterThing.tsx
  src/components/ranking/EmotionsChart.tsx
  src/components/ranking/FilterMenu.tsx
  src/components/ranking/FusionComp/MWreportCard.tsx
  src/components/ranking/FusionComp/TimeFilterGroup.tsx
  src/components/ranking/Report.tsx
  src/components/ranking/TimeFilter.tsx
  src/components/ranking/TopThreeCard.tsx
  src/components/ranking/TopicChart.tsx
  src/components/ranking/WorsenedThing.tsx
  src/components/ranking/solution.tsx
  src/constants/ranking/ChartOptions.ts
  src/constants/ranking/Line.ts
  src/store/store.ts
  tailwind.config.ts
Labels: 원택, feat, css
